### ISSUE TITLE
Add OpenRC init script

### ISSUE THREAD

**Issue by ghost** [CameronNemo/brmgr#2]
Just to let you know that I've just written a Gentoo package for brmgr at https://github.com/hsoft/portage-overlay/tree/master/net-misc/brmgr . It includes an OpenRC init script.

I have barely tested it yet, so I think it's a bit early for a PR, but if it works well, I'll submit a PR for it.

**Comment by CameronNemo** [comment]
pushed a tag, thanks for your contribution!
